#deploy-to-azure-web-app
name: DeployToAzureWebApp

on:
  push:
    branches:
      - 'master'
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - name: Build and publish with dotnet
        working-directory: SampleProj_TestWeb/SampleProj_TestWeb/
        run: |
          dotnet build --configuration Release
          dotnet publish -c Release -o publish
